FRS_MONTAGEM_MANUTENÇÕES/FRS_MONTAGEM_MANUTENÇÕES/Models/Topico.cs
using Microsoft.EntityFrameworkCore;
using Repository;

namespace FRS_Montagens_e_Manutenção.Models
{
    public class Topico
    {
        #region Getters Setters
        public int Id { get; set; }
        public string Nome { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime? DataTermino { get; set; }

        public virtual Pedido Pedido { get; set; }
        public int PedidoId { get; set; }

        public virtual List<SubTopico> SubTopicos { get; set; }
        #endregion

        #region Construtores
        #endregion

        #region Metodos
        public List<Topico> BusccarPorIdPedido(Context context, int id)
        {
            List<Topico> topicos = context.Topicos.Where(a => a.PedidoId == id).ToList();
            return topicos;
        }

        public Topico BuscarPorId(Context context, int Id)
        {
            Topico topico = context.Topicos.Where(a => a.Id == Id).FirstOrDefault();
            return topico;
        }

        public void Alterar(Context context)
        {
            context.Entry(this).State = EntityState.Modified;
            context.SaveChanges();
        }

        public void RemoveRangeSubTopicos(Context context)
        {
            context.SubTopicos.RemoveRange(this.SubTopicos);
            context.SaveChanges();
        }

        public void Remover(Context context)
        {
            context.Topicos.Remove(this);
            context.SaveChanges();
        }
        #endregion
    }
}

FRS_MONTAGEM_MANUTENÇÕES/FRS_MONTAGEM_MANUTENÇÕES/Controllers/SubTopicoController.cs
using FRS_Montagens_e_Manutenção.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repository;

namespace FRS_MONTAGEM_MANUTENÇÕES.Controllers
{
    public class SubTopicoController : Controller
    {
        private Context _context;

        public SubTopicoController(Context context)
        {
            _context = context;
        }

        public IActionResult Edit(int id)
        {
            SubTopico subTopico = new SubTopico().BuscarPorId(_context, id);
            return View(subTopico);
        }

        [HttpPost]
        public ActionResult Edit(SubTopico subTopicoAlterado)
        {
            try
            {
                SubTopico subTopico =
                    new SubTopico().BuscarPorId(_context, subTopicoAlterado.Id);

                subTopico.Nome = subTopicoAlterado.Nome;
                subTopico.DataInicio = subTopicoAlterado.DataInicio;
                subTopico.DataTermino = subTopicoAlterado.DataTermino;

                subTopico.Alterar(_context);

                var topico = _context.Topicos.Where(a => a.Id == subTopico.TopicoId).FirstOrDefault();
                var pedido = _context.Pedidos.Where(a => a.Id == topico.Id).FirstOrDefault();

                return RedirectToAction("ClientePedidos", "PerfilFuncionario", new { id = pedido.ClienteId });
            }
            catch
            {
                return View();
            }
        }

        public IActionResult ConfirmDelete(int id)
        {
            var Subtopicos = _context.SubTopicos.FirstOrDefault(p => p.Id == id);
            if (Subtopicos == null)
            {
                return NotFound();
            }

            return View(Subtopicos);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                var subTopico = _context.SubTopicos.FirstOrDefault(t => t.Id == id);
                if (subTopico != null)
                {
                    subTopico.Remover(_context);

                    _context.SaveChanges();
                }
                return RedirectToAction("Index", "PerfilFuncionario");
            }
            catch (DbUpdateException ex)
            {
                Console.WriteLine("Erro ao salvar alterações: " + ex.InnerException?.Message);
                return View();
            }
        }
    }
}

FRS_MONTAGEM_MANUTENÇÕES/FRS_MONTAGEM_MANUTENÇÕES/Controllers/TopicoController.cs
using FRS_Montagens_e_Manutenção.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repository;

namespace FRS_MONTAGEM_MANUTENÇÕES.Controllers
{
    public class TopicoController : Controller
    {
        private Context _context;

        public TopicoController(Context context)
        {
            _context = context;
        }

        public IActionResult Edit(int id)
        {
            Topico topico = new Topico().BuscarPorId(_context, id);
            topico.SubTopicos = new SubTopico().BusccarPorIdTopico(_context, topico.Id);
            return View(topico);
        }

        [HttpPost]
        public ActionResult Edit(Topico topicoAlterado)
        {
            try
            {
                Topico topico =
                    new Topico().BuscarPorId(_context, topicoAlterado.Id);

                topico.Nome = topicoAlterado.Nome;
                topico.DataInicio = topicoAlterado.DataInicio;
                topico.DataTermino = topicoAlterado.DataTermino;

                topico.Alterar(_context);

                var pedido = _context.Pedidos.Where(a => a.Id == topico.Id).FirstOrDefault();

                return RedirectToAction("ClientePedidos", "PerfilFuncionario", new { id = pedido.ClienteId });
            }
            catch
            {
                return View();
            }
        }

        public IActionResult ConfirmDelete(int id)
        {
            var topico = _context.Topicos.FirstOrDefault(p => p.Id == id);
            if (topico == null)
            {
                return NotFound();
            }

            return View(topico);
        }

        [HttpPost]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                var topico = _context.Topicos
                    .Include(t => t.SubTopicos)
                    .FirstOrDefault(t => t.Id == id);
                if (topico != null)
                {
                    if (topico.SubTopicos != null)
                    {
                        topico.RemoveRangeSubTopicos(_context);
                    }

                    topico.Remover(_context);

                    _context.SaveChanges();
                }
                return RedirectToAction("Index", "PerfilFuncionario");
            }
            catch (DbUpdateException ex)
            {
                Console.WriteLine("Erro ao salvar alterações: " + ex.InnerException?.Message);
                return View();
            }
        }
    }
}

FRS_MONTAGEM_MANUTENÇÕES/FRS_MONTAGEM_MANUTENÇÕES/Views/Topico/ConfirmDelete.cshtml
@using FRS_Montagens_e_Manutenção.Models

@model Topico
<main class="d-flex flex-column align-items-center">
    <form asp-action="DeleteConfirmed" asp-controller="Topico" method="post" id="pedidoForm" class="formulario col-9 my-5">
        <h2 style="color: #ffc846">Confirmação de Exclusão</h2>
        <p style="color: #ffc846">Você tem certeza de que deseja excluir o pedido <strong>@Model.Nome</strong>?</p>
        <div>
            <input type="hidden" asp-for="Id" />
            <button class="continuar fw-bold py-2 px-4 d-flex align-items-center justify-content-evenly" type="submit">Confirmar Exclusão</button>
        </div>
    </form>
</main>

FRS_MONTAGEM_MANUTENÇÕES/FRS_MONTAGEM_MANUTENÇÕES/Views/Topico/Edit.cshtml
@using FRS_Montagens_e_Manutenção.Models;

@model Topico

<style>
    .bottom-border-white td {
        border-bottom: 1px solid #ffffff; /* Borda inferior branca para cada célula */
    }
</style>

<main class="container">
    <a href="javascript:void(0);" onclick="window.close();" class="voltar-link">
        <svg width="20" height="22" viewBox="0 0 20 22" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M14.125 1.25L4.875 10.5L14.125 19.75" stroke="#FFC846" stroke-width="3" />
        </svg>
        Voltar
    </a>

    <form asp-action="Edit" class="formulario" style="width: 95%;">
        <div class="d-flex justify-content-between" style="width: 80%;">
            <span style="width: 65%;">
                <h3>Nome do Tópico</h3>
                <input type="text" asp-for="Nome">
            </span>
        </div>

        <div class="d-flex justify-content-between" style="width: 45%;">
            <span>
                <h3>Data de Inicio</h3>
                <input type="date" asp-for="DataInicio">
            </span>
            <span>
                <h3>Data de Término</h3>
                <input type="date" asp-action="DataFim">
            </span>
        </div>
        <br>
        <table class="tabela-topicos" width="100%">
            <thead>
                <tr>
                    <th>Nome do Tópico</th>
                    <th>Duração</th>
                    <th>Início</th>
                    <th>Término</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var topico in Model.SubTopicos)
                {
                    <tr class="nome-proj bottom-border-white">
                        <td>@topico.Nome</td>
                        <td>@((topico.DataTermino - topico.DataInicio)?.Days ?? 0) dias</td>
                        <td>@topico.DataInicio.ToString("dd/MM/yy")</td>
                        <td>@(topico.DataTermino.HasValue ? topico.DataTermino?.ToString("dd/MM/yy") : "Não definido") </td>
                        <td>
                            <a href="@Url.Action("Edit", "SubTopico", new { id = topico.Id })" target="_blank">Editar</a>
                            <a href="@Url.Action("ConfirmDelete", "SubTopico", new { id = topico.Id })" target="_blank">Excluir</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="edit-btn">
            <button onclick="window.close();" style="background-color: #171717; color: #ffc846; border: solid 0.5px #ffc846;">
                Cancelar
            </button>
            <button type="submit">Salvar</button>
        </div>
    </form>
</main>